events {
    worker_connections 1024;
}

http {
    # =========================================================================
    # 1. СЕКЦИЯ ЛИМИТОВ
    # =========================================================================
    limit_req_zone $binary_remote_addr zone=payment_views_limit:10m rate=3r/s;

    # Блокировка ботов по User-Agent
    map $http_user_agent $blocked_ua {
        default 0;
        ~*libredtail-http 1;
        ~*zgrab 1;
        ~*masscan 1;
        ~*nmap 1;
        ~*ThinkPHP 1;
        ~*Go-http-client 1;
    }

    # Редирект с HTTP на HTTPS
    server {
        listen 80;
        server_name calendar2.duckdns.org;

        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log warn;

        return 301 https://$host$request_uri;
    }


    server {
        listen 443 ssl;
        server_name calendar2.duckdns.org;

        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log warn;

        # Пути к сертификатам Certbot
        ssl_certificate     /etc/letsencrypt/live/calendar2.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/calendar2.duckdns.org/privkey.pem;

        # Оптимизация SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Блокировка ботов
        if ($blocked_ua) {
            return 444;
        }

        # =====================================================================
        # ЗАЩИТА ВЕБХУКА РОБОКАССЫ (Result URL)
        # =====================================================================




        location / {
            proxy_pass http://localhost:8080;
        }

        # Хелсчек Nginx
        location /nginx-health {
            access_log off;
            return 200 'nginx ok\n';
        }

        location ^~ /.well-known/acme-challenge/ {
            root /var/www/letsencrypt;
        }

    }
}